name: Deploy Prod Tencent bitcode-lab.com
run-name: ${{ github.actor }} trigger by ${{github.event_name}}
on: [workflow_dispatch]
jobs:
  build-application:
    runs-on: ubuntu-latest
    name: "Build and Test Code"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - run: npm install
      - name: build
        run: npm run build
        env:
          CI: false

  move-build-folder:
    name: "Move Build to Tencent temp folder"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "move build to Tencent temp"
        uses: appleboy/scp-action@master
        with:
          host: bitcode-lab.com
          username: ubuntu
          key: ${{ secrets.TENCENT_CLOUD_SECRET }}
          port: 22
          source: "build/*"
          target: "~/temp/home"
