name: Deploy Prod Tencent bitcode-lab.com
run-name: ${{ github.actor }} trigger by ${{github.event_name}}
on: [push, workflow_dispatch]
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: "prepare folders and misc"
    steps:
      - run: mkdir ../temp_build

  create-mock:
    runs-on: ubuntu-latest
    name: "prepare mock files"
    steps:
      - run: cd ../temp_build
      - run: touch hello1.txt
      - run: touch hello2.txt
      - run: mkdir sub
      - run: touch sub_hello.txt

  # build-application:
  #   runs-on: ubuntu-latest
  #   name: "Build and Test Code"
  #   needs: prepare
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "14.x"
  #     - run: npm install
  #     - name: build
  #       run: npm run build
  #       env:
  #         CI: false
  #     - name: "move build to local temp"
  #       run: mv build/* ../temp_build

  move-build-folder:
    name: "Move Build to Tencent temp folder"
    runs-on: ubuntu-latest
    needs: [build-application, prepare]
    steps:
      - name: "move build to Tencent temp"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.TENCENT_CLOUD_SSH_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_KEY }}
          port: ${{ secrets.PORT }}
          source: "../temp_build/*"
          target: "~/temp/home"
