name: Deploy Prod Tencent bitcode-lab.com
run-name: ${{ github.actor }} trigger by ${{github.event_name}}
on: [workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: "Build and Test Code"
    strategy:
      matrix:
        node: ["12.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build

  deploy-build:
    name: "deploy build to Tenecet"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: bitcode-lab.com
          username: ubuntu
          key: ${{ secrets.TENCENT_CLOUD_SECRET }}
          port: 22
          script: |
            whoami
            ls -al
